"""add_telegram_token_to_settings

Revision ID: d46c98c8de63
Revises: d9975978b6be
Create Date: 2026-06-14 19:54:16.028689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd46c98c8de63'
down_revision: Union[str, Sequence[str], None] = 'd9975978b6be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('telegram_token_id', sa.String(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'telegram_token_id')
    # ### end Alembic commands ###
