"""change_disk_to_json

Revision ID: d9975978b6be
Revises: 63686a148a6f
Create Date: 2026-06-14 00:55:11.220246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9975978b6be'
down_revision: Union[str, Sequence[str], None] = '63686a148a6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('metrics', 'disk',
            existing_type=sa.DOUBLE_PRECISION(precision=53),
            type_=sa.JSON(),
            existing_nullable=False,
            postgresql_using='disk::text::json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('metrics', 'disk',
               existing_type=sa.JSON(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    # ### end Alembic commands ###
